name: Despliegue en Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy en VPS
    runs-on: ubuntu-latest
    steps:
      - name: Configurar clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Iniciar el agente SSH y agregar la clave
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          
          # Evitar confirmaciones al conectarse por SSH
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Desplegar en VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /usr/local/lsws/Example/html/productly
            git fetch origin main
            git reset --hard origin/main
